### ISSUE TITLE
running communication bear raises exception 

### ISSUE THREAD

**Issue by abh3po** [coala-analyzer/coala-tutorial#1]
Running the communication bear raises the following exception, maybe its limited to my machine, though I've followed the instructions in the tutorial closely so i don't think that should be the case.

Bear CommunicationBear failed to run. Take a look at debug messages for further information.
[DEBUG][15:04:02] The bear CommunicationBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/coalib/bears/Bear.py", line 95, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/usr/local/lib/python3.4/dist-packages/coalib/bears/Bear.py", line 88, in run_bear_from_section
    return self.run(_args, *_kwargs)
  File "/home/abhay/coala/coala-tutorial/bears/CommunicationBear.py", line 21, in run
    file=filename)]
  File "/usr/local/lib/python3.4/dist-packages/coalib/misc/Decorators.py", line 298, in decorated
    return function(_args, *_kwargs)
TypeError: **init**() got an unexpected keyword argument 'file'

**Comment by sils** [comment]
@abhsag24 hi, thanks for reporting, I'll investigate this today!

**Comment by sils** [comment]
@abhsag24 also what coala version are you running? `coala --version`

**Comment by sils** [comment]
@abhsag24 hey, I fixed the bear! Just do a `git pull` on the tutorial and it should work. Feel free to contact us for any further assistance you need :)

**Comment by abh3po** [comment]
thanks and did the tutorial need to be updated as well?(since i couldn't follow it further after the error) or is it fine as it is?

**Comment by sils** [comment]
Hi,

The tutorial should work as it is if there are no further problems, I
didn't have time to retest the whole thing.

**Comment by sils** [comment]
@abhsag24 join us on https://gitter.im/coala-analyzer/coala if you have any further question, that's simpler :)
