### ISSUE TITLE
Redundant space before exclamation mark

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-tutorial#5]
in src/main.c there shouldn't be a space before the exclamation mark.

**Comment by SaurabhSandav** [comment]
Hello! I would like to get assigned to this issue

**Comment by adtac** [comment]
@SaurabhSandav assigned you :+1:

**Comment by SanketDG** [comment]
Fixed in https://github.com/coala-analyzer/coala-tutorial/commit/ae96bf9dc7206003b3e14b884e227c7495ebb07a
